# Generated by Django 5.2.8 on 2025-11-26 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("re_agent_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="bien",
            old_name="titre",
            new_name="bien_adresse",
        ),
        migrations.RenameField(
            model_name="bien",
            old_name="adresse",
            new_name="bien_complement_adresse",
        ),
        migrations.RenameField(
            model_name="bien",
            old_name="created_at",
            new_name="bien_created_at",
        ),
        migrations.RenameField(
            model_name="bien",
            old_name="description",
            new_name="bien_description",
        ),
        migrations.RenameField(
            model_name="bien",
            old_name="prix",
            new_name="bien_honoraires",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="created_at",
            new_name="contact_created_at",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="email",
            new_name="contact_email",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="nom",
            new_name="contact_name",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="telephone",
            new_name="contact_telephone",
        ),
        migrations.RemoveField(
            model_name="bien",
            name="mandat",
        ),
        migrations.RemoveField(
            model_name="bien",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="bien",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="bien",
            name="bien_charge_honoraire",
            field=models.CharField(
                choices=[("vendeur", "Vendeur"), ("acquéreur", "Acquéreur")],
                default="acquéreur",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="bien",
            name="bien_charge_mensuelle",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="bien",
            name="bien_contacts",
            field=models.ManyToManyField(blank=True, to="re_agent_app.contact"),
        ),
        migrations.AddField(
            model_name="bien",
            name="bien_diffusé",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bien",
            name="bien_info_complémentaire",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VEFA", "VEFA"),
                    ("occupé", "Occupé"),
                    ("villa", "Villa"),
                    ("chalet_bois", "Chalet en bois"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bien",
            name="bien_numéro_clé",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bien",
            name="bien_négociateur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bien",
            name="bien_prix",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bien",
            name="bien_prix_hors_honoraires",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bien",
            name="bien_status",
            field=models.CharField(
                choices=[
                    ("actif", "Actif"),
                    ("estimation", "Estimation"),
                    ("archivé", "Archivé"),
                ],
                default="disponible",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="bien",
            name="bien_surface",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bien",
            name="bien_surface_terrain",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bien",
            name="bien_taux_commision",
            field=models.FloatField(blank=True, default=4.5, null=True),
        ),
        migrations.AddField(
            model_name="bien",
            name="bien_taxe_foncière",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="bien",
            name="bien_taxe_habitation",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="bien",
            name="bien_titre",
            field=models.CharField(default="Maison de reve", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bien",
            name="bien_type",
            field=models.CharField(
                choices=[
                    ("appartement", "Appartement"),
                    ("maison", "Maison"),
                    ("terrain", "Terrain"),
                    ("local_commercial", "Local Commercial"),
                    ("garage", "Garage"),
                    ("parking", "Parking"),
                    ("immeuble", "Immeuble"),
                    ("fond_de_commerce", "Fond de Commerce"),
                    ("ensemble_immobilier", "Ensemble Immobilier"),
                ],
                default="appartement",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="bien",
            name="bien_type_tansaction",
            field=models.CharField(
                choices=[("vente", "Vente"), ("location", "Location")],
                default="vente",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_adress",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_commentar",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_complement_adress",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_cr_bedroom_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_cr_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_cr_room_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_cr_surface",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_cr_surface_terrain",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_cr_type_estatse",
            field=models.CharField(
                choices=[
                    ("appartement", "Appartement"),
                    ("maison", "Maison"),
                    ("terrain", "Terrain"),
                    ("local_commercial", "Local Commercial"),
                    ("garage", "Garage"),
                    ("parking", "Parking"),
                    ("immeuble", "Immeuble"),
                    ("fond_de_commerce", "Fond de Commerce"),
                    ("ensemble_immobilier", "Ensemble Immobilier"),
                ],
                default="appartement",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_cr_type_search",
            field=models.CharField(
                choices=[("vente", "Vente"), ("location", "Location")],
                default="vente",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_first_name",
            field=models.CharField(default="Antoine", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_nego",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_status",
            field=models.CharField(
                choices=[("actif", "Actif"), ("archivé", "Archivé")],
                default="actif",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("acquéreur", "Acquéreur"),
                    ("locataire", "Locataire"),
                    ("propriétaire", "Propriétaire"),
                    ("notaire", "Notaire"),
                    ("syndic", "Syndic"),
                ],
                default="acheteur",
                max_length=50,
            ),
        ),
    ]
